---
- name: Install fish
  ansible.builtin.apt:
    name: fish

- name: Default shell
  ansible.builtin.user:
    name: vagrant
    shell: /usr/bin/fish

- name: Add alias for kubectl
  become: false
  ansible.builtin.lineinfile:
    path: .config/fish/config.fish
    line: alias k "kubectl"
    create: true
