- name: Create cluster
  hosts: cluster
  gather_facts: true
  strategy: free
  become: true
  roles:
    - fish
    - containerd
    - kubernetes

- name: Configure masters
  hosts: masters
  gather_facts: true
  become: true
  roles:
    - masters
    # - cni

- hosts: workers
  gather_facts: true
  become: true
  roles:
    - nodes

# - name: Install stuffs
#   hosts: masters
#   gather_facts: true
#   become: true
#   roles:
#     - helm
#     - nginx
#     - metallb
