---
modules:
  - name: overlay
  - name: br_netfilter

parameters:
  - name: net.bridge.bridge-nf-call-iptables
  - name: net.ipv4.ip_forward
  - name: net.bridge.bridge-nf-call-ip6tables

docker_repo_url: https://download.docker.com/linux
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_gpg_key: "{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg"
