---
- name: Check if kubelet.conf exists
  ansible.builtin.stat:
    path: "/etc/kubernetes/kubelet.conf"
  register: kubelet_conf

- name: Join the node to cluster
  ansible.builtin.command: "{{ hostvars['node-1']['join_command']['stdout'] }}"
  when:
    - not kubelet_conf.stat.exists
