---
- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: "{{ item.key }}"
    state: present
  with_items: "{{ gpg_keys }}"

- name: Add apt repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items: "{{ repositories }}"

- name: Install Kubernetes
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: present
    update_cache: true
  with_items: "{{ packages }}"

- name: Disable swap
  # ansible.builtin.shell: "swapoff -a"
  ansible.builtin.command: "swapoff -a"
  changed_when: false

- name: Remove current swaps from stabs
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: '(?i)^([^#][\S]+\s+(none|swap)\s+swap.*)'
    line: '# \1'
    backrefs: true
    state: present

- name: Disable swappiness
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ swap }}"


- name: Reload kubelet
  ansible.builtin.systemd:
    name: kubelet
    daemon_reload: true
    enabled: true
