# - name: Install package
#   ansible.builtin.apt:
#     name: containerd
#     state: present
#     update_cache: true
#
# - name: Configure /etc/modules-load.d/containerd.conf
#   ansible.builtin.blockinfile:
#     path: /etc/modules-load.d/containerd.conf
#     create: true
#     block: |
#       overlay
#       br_netfilter
#
# - name: Add modules
#   community.general.modprobe:
#     name: "{{ item.name }}"
#     state: present
#   with_items: "{{ modules }}"
#
# - name: Set sysctl parameters
#   ansible.posix.sysctl:
#     name: "{{ item.name }}"
#     value: "1"
#     sysctl_set: true
#     state: present
#     reload: true
#   with_items: "{{ parameters }}"
#
# - name: Create a directory
#   ansible.builtin.file:
#     path: /etc/containerd
#     state: directory
#     mode: 0755
#
# - name: Generate a default configuration
#   ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
#   args:
#     creates: /etc/containerd/config.toml
#   notify: Restart containerd
#
# - name: Enable containerd
#   ansible.builtin.systemd:
#     name: containerd
#     state: started
#     enabled: true

# - name: 
